JDP210304-13
hacker-msl/project-jdp-2103-04 pull request #12
Opened 2021-04-04 13:20 UTC by ete02

Create Group class with entity implementation.
Entity was named "group_product" as name "group"  is key for SQL

2021-04-04 17:11 UTC, hacker-msl requested changes

2021-04-04 17:11 UTC, hacker-msl commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.16'
w każdym PR to jest zrobione inaczej, więc po merge pewnie będą jakieś babole i trzeba będzie naprawiać zaleznosci

2021-04-04 17:11 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/Group.java
> +@Entity (name = "group_product")
żeby było bardziej po angielsku powinno być product_group

2021-04-04 17:11 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/Group.java
> +    public void  clearId (Long id) {
a to w jakim celu ?

2021-04-04 17:11 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>  public class GroupController {
co w tym PR robi kontroler ? to ma być PR z encją 

2021-04-04 17:11 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupDto.java
> +public class GroupDto {
co tu robi DTO? to ma być PR z encją...

2021-04-04 22:55 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/Group.java
> +    public void  clearId (Long id) {
oby upewnić się, że zostanie utworzony nowy obiekt a nie zostanie zmodyfikowany istniejący, gdy bedzię zawierać pole id

2021-04-04 22:57 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>  public class GroupController {
to jest pierwszy task, ale nie umiem wyslać tylko jedną nową klasę a wysyła sie wszystko co zrobiłem

2021-04-04 22:57 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/GroupDto.java
> +public class GroupDto {
to jest pierwszy task, ale nie umiem wyslać tylko jedną nową klasę a wysyła sie wszystko co zrobiłem dotąd

2021-04-04 23:01 UTC, ete02 commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.16'
to rozumiem, mamy z chlopaki usalić jedyny wzorzec build.gradle?

2021-04-05 16:58 UTC, hacker-msl requested changes

2021-04-05 16:58 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/Group.java
> +package com.kodilla.ecommercee;
może zróbmy jakiś pakiet pod te klasę i inne? Sugeruję pakiet com.kodilla.ecommercee.domain

2021-04-05 16:58 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>  package com.kodilla.ecommercee;
może zróbmy jakiś pakiet pod te klasę i inne? Sugeruję pakiet com.kodilla.ecommercee.controller

2021-04-05 16:58 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>  public class GroupController {
użyj git add /sciezka/do/pliku/do/dodania.java

2021-04-05 21:15 UTC, closed without merging