Jdp210304 4
hacker-msl/project-jdp-2103-04 pull request #13
Opened 2021-04-05 12:23 UTC by Mateusz32

- Poprawiłem OrderController przy @RequestMapping zmieniłem na ("/v1/order");
- zaktualizowałem OrderDto, aby pasowało do Encji Order;

2021-04-05 16:49 UTC, hacker-msl requested changes

2021-04-05 16:49 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    @PutMapping
w create dałeś "consumes" a tutaj nie

2021-04-05 16:49 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +        this.orderNumber=orderNumber;
przy pozostałych polach dawałeś spacje.

2021-04-05 16:57 UTC, hacker-msl requested changes

2021-04-05 16:57 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/OrderController.java
>  package com.kodilla.ecommercee;
może zróbmy jakiś pakiet pod te klasę i inne? Sugeruję pakiet com.kodilla.ecommercee.controller

2021-04-06 16:54 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
> +    @PutMapping
fix

2021-04-06 16:55 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +        this.orderNumber=orderNumber;
fixed

2021-04-06 16:55 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/OrderController.java
>  package com.kodilla.ecommercee;
fixed

2021-04-06 19:24 UTC, hacker-msl approved these changes

2021-04-06 19:24 UTC, merged