First draft User entity
hacker-msl/project-jdp-2103-04 pull request #18
Opened 2021-04-06 15:50 UTC by robertgluszkiewicz

1. Zrobiłem szkic encji User do sprawdzenia.
2. Widzę, że będziemy musieli pomiędzy sobą jako członkowie zespołu ustalić relacje encji, że by nie robić tego dwa razy. Czy User może mieć 2 koszyki, czy tylko jeden itp.

2021-04-06 19:15 UTC, hacker-msl requested changes

2021-04-06 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "ID", unique = true)
adnotacja column jest niepotrzebna tutaj.

2021-04-06 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column (name = "USERNAME", unique = true)
wyrzuć name z adnotacji column

2021-04-06 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column (name = "USER_VALIDATION")
adnotacja column jest niepotrzebna tutaj.

2021-04-06 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column (name = "USER_KEY")
adnotacja column jest niepotrzebna tutaj.

2021-04-07 16:10 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "ID", unique = true)
Zgadza się.

2021-04-07 16:10 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column (name = "USERNAME", unique = true)
OK

2021-04-07 16:10 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column (name = "USER_VALIDATION")
OK

2021-04-07 16:10 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column (name = "USER_KEY")
OK

2021-04-07 16:11 UTC, robertgluszkiewicz commented
Usunąłem niepotrzebne adnotacje.

2021-04-07 18:45 UTC, hacker-msl commented
brakuje tutaj relacji chociażby do Cart, ale to możemy pododawać później i dookreślić kierunek i krotność relacji.

2021-04-07 18:48 UTC, merged