Jdp210304 14
hacker-msl/project-jdp-2103-04 pull request #19
Opened 2021-04-06 17:05 UTC by KacperB83

2021-04-06 19:22 UTC, hacker-msl requested changes

2021-04-06 19:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +@RequiredArgsConstructor
to tutaj nie jest potrezbne

2021-04-06 19:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/repository/CartRepository.java
> +public interface CartRepository extends CrudRepository<Cart, Long> {
rozszerz JpaRepository zzamiast CrudRepository i wyrzuć te metody - gdyż nie są potrzebne

2021-04-07 13:50 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
Dodałem encję Product bo bez tego nie tworzyła się ta dodatkowa encja products_in_cart. Kwestia tego jak ona wygląda - kolumna, którą myślałem, że nazywam dzięki @MapKeyColumn = "product" nazywa się products_in_cart_key :(

2021-04-07 19:08 UTC, hacker-msl requested changes

2021-04-07 19:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
>  public class CartController {
1. ta klasa tutaj nie jest potrzebna
2. ta klasa jest w zlym pakiecie
3. usuniesz ją ? :-)

2021-04-07 19:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Entity(name = "carts")
z dużych liter ? tak jak uzgodniliśmy podczas ostatniego spotkania

2021-04-07 19:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @Column(name = "id")
ta adnotacja nie jest potrzebna

2021-04-07 19:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    public int getCartValue() {
zakomentowany kod wywalamy

2021-04-07 19:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @Column(name = "total_value")
nie do końca rozumiem skąd ta rozbieżność nazw? nazwa total_value czy total_price wydaje mi się dużo bardziej intuicyjna niż cartValue. Może wyrzuć te adnotację i po prostu zmień nazwę pola w klasie na totalCartValue ?

2021-04-07 19:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +public class Product {
co tutaj robi emcja Product ? te encję robi @brzezyn  w innym zadaniu https://projects.kodilla.com/browse/JDP210304-12

2021-04-07 19:52 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/CartController.java
>  public class CartController {
Jest pusta i pobrała się z main chyba. Usuwam

2021-04-07 20:10 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @Column(name = "total_value")
Ok. Zmienię na totalValue.

2021-04-07 20:11 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +public class Product {
Zrobiłem ją tylko w takim celu żeby zobaczyć jakie tabele mi się utworzą. Wyrzucam

2021-04-09 20:10 UTC, hacker-msl approved these changes

2021-04-09 20:10 UTC, merged