Jdp210304 12
hacker-msl/project-jdp-2103-04 pull request #23
Opened 2021-04-06 21:56 UTC by brzezyn

Pierwsza propozycja encji Product

2021-04-07 19:15 UTC, hacker-msl requested changes

2021-04-07 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(name = "PRODUCTID", unique = true)
ta adnotacja nie jest potrzebna

2021-04-07 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(name = "NAME")
ta adnotacja nie jest potrzebna

2021-04-07 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(name = "DESCRIPTION")
ta adnotacja nie jest potrzebna

2021-04-07 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(name = "PRICE")
ta adnotacja nie jest potrzebna

2021-04-07 21:29 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(name = "PRICE")
już wywalona

2021-04-08 18:18 UTC, hacker-msl requested changes

2021-04-08 18:18 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(unique = true)
tutaj wystarczy 
@Id
@GeneratedValue 

te 2 adnotacje gwarantują, żę jest unique oraz @NotNull

2021-04-08 22:30 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    @Column(unique = true)
okej, już usunięte

2021-04-09 19:18 UTC, hacker-msl requested changes
Projekt się nie buduje... 

> Task :compileJava
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:3: error: package lombok does not exist
import lombok.AllArgsConstructor;
             ^
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:4: error: package lombok does not exist
import lombok.Getter;
             ^
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:9: error: cannot find symbol
@Getter
 ^
  symbol: class Getter
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:10: error: cannot find symbol
@AllArgsConstructor
 ^
  symbol: class AllArgsConstructor
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:32: error: cannot find symbol
    private List<Cart> cartList;
            ^
  symbol:   class List
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:32: error: cannot find symbol
    private List<Cart> cartList;
                 ^
  symbol:   class Cart
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:36: error: cannot find symbol
    private Group group;
            ^
  symbol:   class Group
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:45: error: cannot find symbol
    private List<OrderItems> orderItems;
            ^
  symbol:   class List
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:45: error: cannot find symbol
    private List<OrderItems> orderItems;
                 ^
  symbol:   class OrderItems
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:39: error: cannot find symbol
            targetEntity = OrderItems.class,
                           ^
  symbol:   class OrderItems
  location: class Product
10 errors

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

2021-04-11 10:34 UTC, hacker-msl commented
1) są konflikty. Rozwiązesz czy ja mam rozwiązać? 
2) nie buduje się projekt: 

           ^
  symbol:   class Group
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:42: error: cannot find symbol
    private List<OrderItems> orderItems;
            ^
  symbol:   class List
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:42: error: cannot find symbol
    private List<OrderItems> orderItems;
                 ^
  symbol:   class OrderItems
  location: class Product
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:36: error: cannot find symbol
            targetEntity = OrderItems.class,
                           ^
  symbol:   class OrderItems
  location: class Product
10 errors

2021-04-11 10:34 UTC, hacker-msl requested changes
do rozwiązania konflikty i problemy z budowaniem

2021-04-11 12:58 UTC, brzezyn commented
Pracuje jeszcze nad tym branchem, daj mi jeszcze trochę czasu jak nie podałam to dam znać

2021-04-11 18:32 UTC, brzezyn commented
Czy te konflikty wynikają z tego, że branch do ticketu z Encją utworzyłem z branch'a od ticketu z Controllerem?
I teraz na branchu Encji usunąłem Controller i zmodyfikowałem klasę Product.
A problem przy budowaniu wynika z tego co zauważyłem z JpaRepository, jak było Crud to wszystko budowało.

2021-04-11 19:00 UTC, closed without merging