JDP210304-13
hacker-msl/project-jdp-2103-04 pull request #25
Opened 2021-04-07 00:15 UTC by ete02

Wprowadziłem zmiany do encji Group zgodnie z komentarzami Mateusza. 
Metoda clear Id (Long id) powstała oby upewnić się, iż zostanie otworzony obiekt a nie zostanie zmodyfikowany istniejący, gdy będzie zawierać pole id
"Posprzatałem branch" od niepotrzebnych klas

2021-04-07 19:14 UTC, hacker-msl requested changes

2021-04-07 19:14 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void  clearId (Long id) {
po raz kolejny pytam co to jest ?

2021-04-07 19:45 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void  clearId (Long id) {
wczesniej pisalem odpowiadalem w PR. Metoda powsatala oby upewnić się, iż zostanie utworzony obiekt a nie zostanie zmodyfikowany istniejacy, gdu bedzie zawierać pole id

2021-04-08 18:16 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +public class Group {
czemu tutaj nie ma @Setter na tej klasie ?

2021-04-08 18:16 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void setName (String name) {
używamy Lomboka. Jeśli chcesz mieć setter tylko do 1 pola, to użyj odpowiedniej adnotacji nad tym polem (nie nad klasą). Natomiast uważam, że ma być w encji @Setter nad klasą.

2021-04-08 18:16 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void  clearId (Long id) {
to jest kompletnie niepotrzebne. Dobrze, że już nie ma.

2021-04-08 18:16 UTC, hacker-msl requested changes
popraw uwagi

2021-04-08 18:27 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void setName (String name) {
dodany @Setter

2021-04-09 19:44 UTC, hacker-msl requested changes

2021-04-09 19:44 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    public void setName (String name) {
ta metoda ma wylecieć... jest @Setter.

2021-04-09 19:44 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    /*@OneToMany(
odkomentuj ten kod i dodaj pustą klasę Product

2021-04-11 10:29 UTC, hacker-msl commented
po pierwsze są konflikty. Rozwiażesz @ete02  czy mam to ja zrobić? 

po drugie nie działa budowanie projektu:

mateo@linux-to0r:~/eclipse-workspace/kodilla-team/project-jdp-2103-04> ./gradlew clean build      

> Task :test

com.kodilla.ecommercee.EcommerceeApplicationTests > contextLoads FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.AnnotationException

com.kodilla.ecommercee.SpringBootJPAIntegrationTest > givenGenericEntityRepository_whenSaveAndRetreiveEntity_thenOK FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.AnnotationException

2 tests completed, 2 failed

2021-04-11 10:35 UTC, hacker-msl requested changes
popraw konflikty i budowanie projektu

2021-04-11 19:36 UTC, hacker-msl requested changes
@ete02 poprawiłem konflikty. Popraw proszę błąd, który występuje podczas budowania projektu 

Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.kodilla.ecommercee.domain.Product.group in com.kodilla.ecommercee.domain.Group.productList
	at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:785)
	at org.hibernate.cfg.annotations.CollectionBinder$1.secondPass(CollectionBinder.java:736)
	at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:54)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1696)
	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1664)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:287)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:904)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741)
	... 64 more

2021-04-12 18:25 UTC, ete02 commented
hej ,poprawiam, ale wciaz mo nie che budowac, w związku z czym nie wysylam PR

2021-04-13 19:21 UTC, hacker-msl approved these changes

2021-04-13 19:21 UTC, merged