JDP210304-2
hacker-msl/project-jdp-2103-04 pull request #26
Opened 2021-04-07 00:34 UTC by ete02

Dodałem return method w @PostMapping w GroupController.
‘’Posprzątałem’’ branch

2021-04-07 19:14 UTC, hacker-msl requested changes

2021-04-07 19:14 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +public class GroupController {
brakuje metody delete ?

2021-04-07 20:03 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +public class GroupController {
nie podałałem celowo. Dodałem zgodnie z wytycznymi

2021-04-07 20:15 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +public class GroupController {
zrobiłem to celowo, uwazam , iz grupa jest bardziej stała. Dodałem @DeleteMapping zgodnie z zapytaniem

2021-04-08 18:25 UTC, hacker-msl requested changes

2021-04-08 18:25 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @DeleteMapping
ma być @DeleteMapping("/{groupId}") i @PathVariable zamiast @RequestParam

2021-04-08 18:39 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @DeleteMapping
zmienione :)

2021-04-09 19:47 UTC, hacker-msl submitted a review, later dismissed

2021-04-09 19:49 UTC, hacker-msl approved these changes
ok

2021-04-09 19:49 UTC, merged