UserRepository created. Restore to main UserController and UserDto.
hacker-msl/project-jdp-2103-04 pull request #33
Opened 2021-04-12 15:33 UTC by robertgluszkiewicz

2021-04-12 17:02 UTC, hacker-msl requested changes

2021-04-12 17:02 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends CrudRepository <User, Long> {
zmień na JpaRepository . Ma to co Crud i o wiele więcej :-) poza tym wszyscy mają u siebie CrudRepository

2021-04-12 17:36 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends CrudRepository <User, Long> {
Zrobiłem. Jest nowy commit.

2021-04-13 18:30 UTC, hacker-msl approved these changes

2021-04-13 18:30 UTC, merged