Rzeczywista Implementacja Cart
hacker-msl/project-jdp-2103-04 pull request #34
Opened 2021-04-12 19:22 UTC by KacperB83

To wstępna implementacja. Trochę pozmieniałem i mam nadzieję, że nie totalnie bez sensu.

2021-04-13 19:25 UTC, hacker-msl requested changes

2021-04-13 19:25 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        CartDto cart = cartMapper.mapToCartDto(cartService.getCart(id).orElseThrow(CartNotFoundException::new));
nienawidzę tak długich linii kodu. Nic nie da się z tego odczytać. Zobacz jak fajnie i czytelnie napisałęś addProductsToCart. Do tego mam wrażenie, że wywołujesz clear na obiekcie transportowym  zamiast na bazie danych. To raczej nie zadziała. Rekordy powinny zniknąć z bazy danych.

2021-04-13 19:29 UTC, hacker-msl requested changes

2021-04-13 19:29 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public CartDto addProductToCart(@RequestBody CartDto cartDto) {
i gdzie tutaj jakiś produkt dodajesz? otrzymujesz dto, które mapujesz na encję i zapisujesz do bazy. Następnie mapujesz z powrotem do Dto. Generalnie to jest otrzymanie i nadpisanie całego koszyka. Albo kod jest do przepisania, albo nazwa.

2021-04-13 19:29 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        Cart cart = cartMapper.mapToCart(cartDto);
tworzysz tutaj Cart, ale w żaden sposób nie informuejsz FE jaki ID ma utworzony koszyk. Skąd zatem FE ma wiedzieć jaki wysłać request w celu np. dodania produktu do koszyka?

2021-04-13 21:45 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        CartDto cart = cartMapper.mapToCartDto(cartService.getCart(id).orElseThrow(CartNotFoundException::new));
poprawione

2021-04-13 21:46 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public CartDto addProductToCart(@RequestBody CartDto cartDto) {
Ok. Fakt brak tu productId. poprawiam

2021-04-13 21:51 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    }*/
Zakomentowałem propozycję metody do tworzenia  new Order. Mam tu jednak wątpliwość czy nie powinien pojawić się tu User? Jak z wartością koszyka - właściwie nowego Order-a?

2021-04-14 18:45 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    }*/
@KacperB83 User powinien być w mojej ocenie w encji Cart. Wtedy wystarczy tutaj sam cartId. 
W mojej ocenie też powinieneś rozpoznawać sytuację taką, gdy z danego Cart już wcześniej powstał Order. Wtedy trzeba rzucać wyjątkiem. No i nie powinieneś tworzyć w kontrolerze nowego obiektu tego samego kontrolera...

2021-04-14 18:47 UTC, hacker-msl requested changes
popraw

2021-04-14 20:57 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +
Nie wiem czy dobrze zrozumiałem Twój komentarz ale mam nadzieję, że jestem bliżej

2021-04-14 20:57 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
>          System.out.println("Id: " + orderDto.getId() + "\n"
Tu w drodze próby wpadł mi Cart do PR - zapomniałem wyczyścić

2021-04-14 20:57 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
Wystarczy id usera?

2021-04-14 20:57 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
czy taki boolean będzie ok? Wykorzystałem go w metodzie createOrderFromCart w kontrolerze

2021-04-15 15:07 UTC, hacker-msl requested changes

2021-04-15 15:07 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
tak nie rób. Wykorzystaj mechanizm Hibernate... zrób User po prostu. 
@Column jest zupełnie zbędne

2021-04-15 15:07 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +
nie, wystarczy relacja do Order w mojej ocenie

2021-04-16 18:59 UTC, hacker-msl requested changes

2021-04-16 18:59 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    private final OrderController orderController;
jeden kontroler nie powinien używać innego. Nie w klasycznym MVC (można zrobić coś podobnego w H-MVC). Jeśli to serio jeset potrzebne, to powinniśmy wydzielić jakąś fasadę. Ewentualnie przenieść więcej do serwisu... bo z tego co pamietam to część zepsołu nie wiedziała co to jest fasada.

2021-04-16 20:16 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    private final OrderController orderController;
Szczerze to w drodze kombinowania jak w CartController utworzyć Order z koszyka wrzuciłem ten OrderController. Domyślałem się, że nie jest to właściwe rozwiązanie - jak w takim razie to ugryźć bo szukałem i nie wiem jak to zrobić. Zwróciłeś uwagę na ostatnią metodę, która ma tworzyć Order? Myślałem, żeby w niej stworzyć nowy OrderDto i przekazać do OrderController ale nie wiem czy top ma sens?

2021-04-16 21:24 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        cartService.saveOrder(order);
Co myślisz o takim rozwiązaniu? Do CartService dodałem dodałem saveOrder.

2021-04-17 17:23 UTC, hacker-msl requested changes

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PutMapping("/{id}/{productId}/{quantity}")
uściślijmy to. Zmień {id} na {cartId}

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        cart.getProductsInCart().clear();
niczego tu nie zapisujesz

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        return cartMapper.mapToCartDto(
ja osobiście nie znoszę takiego zapisu... moje zdanie podziela też autor książki "Clean code" (a raczej ja jego ;) ). Wiem, że tak jest w materiałach z Kodilli... natomiast to nie oznacza, że to jest dobrze. Ja sugeruję: 
Cart cart = cartService.getCart(id)
         .orElseThrow(CartNotFoundException::new);
return cartMapper.mapToCartDto(car);

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void  /*ResponseEntity<Void> */createCart(@RequestBody CartDto cartDto) {
skąd ten zakomentowany kod ?

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        /*URI createCart = ServletUriComponentsBuilder.fromCurrentRequest()
co tutaj ma robić ten zakomentowany kod? to jest potrzebne ?

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @NotNull
to nie jest potrzebne...

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @ManyToOne()
co robią tutaj nawiasy () ?

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Map<Long , Integer> productsInCart = new HashMap<>();
dlaczego zmieniłeś na trzymanie samych IDków? To może powodować problemy, jeśli w trakcie przygotowywania koszyka jakiś produkt zniknie ze sklepu. Nie ma powiązania w bazie, więc może być ciężko dojść do tego, że czegoś brakuje.

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private Map<Long, Integer> productsInCart;
jeśli w Dto trzymamy mapę z ID, to potem na FE trzeba będize dla każdego z tych ID osobno strzelić na BE po dane danego produktu

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
w DTO powinno raczej być UserDto userDto (wtedy pisanie mapperów jest trudniejsze) lub Long userId (ale wtedy trzeba osobno strzelać na BE po dane).

2021-04-17 17:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private Order order;
tak jak przy User

2021-04-17 17:23 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/cartTest/CartTestSuite.java
> +    public void contextLoads() {
usuń to

2021-04-17 17:23 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/cartTest/CartTestSuite.java
> +    private String createURLWithPort(String uri) {
ten sakomentowany kod musi wylecieć przed merge

2021-04-17 19:55 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PutMapping("/{id}/{productId}/{quantity}")
ok

2021-04-17 19:55 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        return cartMapper.mapToCartDto(
zmienione

2021-04-17 19:55 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    public void  /*ResponseEntity<Void> */createCart(@RequestBody CartDto cartDto) {
do testów kombinowałem. 
wywalony

2021-04-17 19:56 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @ManyToOne()
wywalone

2021-04-17 19:56 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Map<Long , Integer> productsInCart = new HashMap<>();
Ok. Wracam do Product w mapie

2021-04-17 19:58 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
ok. Zmieniam na UserDto

2021-04-17 19:58 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private Order order;
ok

2021-04-17 19:58 UTC, KacperB83 commented on src/test/java/com/kodilla/ecommercee/cartTest/CartTestSuite.java
> +    private String createURLWithPort(String uri) {
ok

2021-04-17 19:59 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        cart.getProductsInCart().clear();
fakt. poprawione

2021-04-17 20:04 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/service/CartService.java
> +        return orderRepository.save(order);
Takie rozwiązanie będzie ok?

2021-04-18 17:13 UTC, hacker-msl requested changes

2021-04-18 17:13 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                    @PathVariable Product product,
1) to nie zadziała, bo w adresie masz productId, a w metodzie product.
2) powinieneś przyjmować jednak productId i sparwdzić, czy taki istnieje
3) jeśli przesyłasz cały obiekt w metodzie to powinno to być Dto, a nie encja

2021-04-18 17:13 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        Cart cart = cartService.getCart(cartId).orElseThrow(CartNotFoundException::new);
nie sprawdzasz czy produkt istnieje w bazie

2021-04-18 19:22 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                    @PathVariable Product product,
ok. Daję zmienną Product w nowym commicie  i z ProductService sprawdzam czy jest dany produkt. Tak będzie ok?

2021-04-18 19:22 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +        Cart cart = cartService.getCart(cartId).orElseThrow(CartNotFoundException::new);
zmieniam

2021-04-19 05:54 UTC, hacker-msl commented
@robertgluszkiewicz    od  dzisiaj Ty jesteś odpowiedzialny za review tego PR (którego autorem jest @KacperB83  ). Do mnie zgłaszacie dopiero jak @Mateusz32   zatwierdzi lub macie odmienne zdanie w pewnej kwestii. Tam jest taki przycisk "re-review", który wygląda jak recycling. 

![image](https://user-images.githubusercontent.com/44570046/115187775-32312000-a0e4-11eb-8196-01a558fbbe44.png)

Pamiętajcie, żeby go użyć.

2021-04-22 18:42 UTC, hacker-msl commented
hej @robertgluszkiewicz i @KacperB83 moge w czyms pomoc ?

2021-04-23 00:30 UTC, robertgluszkiewicz submitted a review, later dismissed
1. Trudno mi pomóc Kacprowi, w miejscach, w których pyta czy rozwiązania jest właściwe.
2. Jedyne co, to wyrzuciłbym z tego PRa testy, bo z tego co widzę metody w repozytorium nie zostały nadpisane, a testy encji są w innym tickecie.

2021-04-23 19:23 UTC, hacker-msl requested changes

2021-04-23 19:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PostMapping(consumes = APPLICATION_JSON_VALUE)
w mojej ocenie ten end-point powinien zwracać ID, żeby bylo wiadomo jakie ID ma stworzony koszyk, gdyż brakuje end-pointu, który zwraca koszyj, który nie został "wypromowany" do zamówienia.

2021-04-23 19:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private UserDto userDto;
zrobiłeś relacje z encji do klasy transportowej UserDto... tak miało być?

2021-04-23 19:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private OrderDto orderDto;
zrobiłeś relacje z encji do klasy transportowej OrderDto... tak miało być?

2021-04-23 19:23 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/cartTest/CartTestSuite.java
> +        assertNotEquals(java.util.Optional.of(0), cartId);
czemu nie zrobisz importu z optionalem?

2021-04-23 19:49 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private UserDto userDto;
Tak zrozumiałem. Powinno być User user?

2021-04-23 19:49 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private OrderDto orderDto;
Tak zrozumiałem. Powinno być Order order?

2021-04-23 20:00 UTC, KacperB83 commented on src/test/java/com/kodilla/ecommercee/cartTest/CartTestSuite.java
> +        assertNotEquals(java.util.Optional.of(0), cartId);
Zrobione

2021-04-23 20:22 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PostMapping(consumes = APPLICATION_JSON_VALUE)
Zerknij czy o to chodziło

2021-04-23 20:25 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                cart.getOrder().getOrderNumber(),
czy tutaj nie powinniśmy podać orderNumber w @PathVariable?

2021-04-24 18:59 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private OrderDto orderDto;
tak

2021-04-24 19:06 UTC, hacker-msl requested changes
branch się nie buduje: 

> Task :compileJava FAILED
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/CartController.java:22: error: cannot find symbol
    private final ProductService productService;
                  ^
  symbol:   class ProductService
  location: class CartController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/CartController.java:17: error: cannot find symbol
@RequiredArgsConstructor
^
  symbol:   class ProductService
  location: class CartController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java:14: error: cannot find symbol
    private UserService userService;
            ^
  symbol:   class UserService
  location: class CartMapper
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
2 actionable tasks: 2 executed

2021-04-24 19:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                cart.getOrder().getOrderNumber(),
po co? id jest unikatowe, order number powinien być nadany z automatu

2021-04-24 20:34 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                cart.getOrder().getOrderNumber(),
Zerknij do encji jest tak:
@Id
    @GeneratedValue
    private Long id;

    @NotNull
    private Long orderNumber;

2021-04-24 20:35 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +                                cart.getOrder().getOrderNumber(),
Pomyślałem, że powinien być dodawany ten orderNumber

2021-04-24 21:13 UTC, KacperB83 commented
Teraz już się buduje. Wszędzie (w mapperze i kontrolerze) zmieniłem na repository User i Order

2021-04-25 18:33 UTC, hacker-msl requested changes
1) błąd testów:
`javax.persistence.EntityNotFoundException: Unable to find com.kodilla.ecommercee.domain.Cart with id 1
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:162)
	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:285)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:180)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:309)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)`

2) warn przy budowaniu: 
`/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Cart.java:32: warning: @Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
    private Map<Product , Integer> productsInCart = new HashMap<>();
                                   ^
1 warning
` trzeba dodać adnotację `@Builder.Default`

2021-04-25 20:52 UTC, KacperB83 commented
Poprawiłem i test działa. Nie udało mi się jednak wpisać @Builder.Default - cały czas krzyczał żeby usunąć Default

2021-04-26 07:41 UTC, hacker-msl requested changes
po zrobieniu merge z maina (były konflikty) jest problem z testami: 

![image](https://user-images.githubusercontent.com/44570046/116046581-818ec780-a673-11eb-926b-fe2f89b352ca.png)

2021-04-26 07:45 UTC, hacker-msl commented
ten błąd z testami pojawił się na **main** możemy robić merge

2021-04-26 07:45 UTC, merged