JDP210304-16
hacker-msl/project-jdp-2103-04 pull request #35
Opened 2021-04-12 21:39 UTC by ete02

First OrderEntity tests

2021-04-13 19:06 UTC, hacker-msl requested changes

2021-04-13 19:06 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    public void findAllOrderTest() {
może dajmy @Transactional na te testy i wywalmy sekcje cleanup?

2021-04-14 20:27 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    public void findAllOrderTest() {
done

2021-04-15 15:04 UTC, hacker-msl commented
@ete02  są konflikty w UserRepository... spróbujesz je rozwiązać ?

2021-04-15 15:05 UTC, hacker-msl requested changes

2021-04-15 15:05 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +package com.kodilla.ecommercee.repository;public interface UserRepository {
ten interfejs UserRepository chyba nie powinien tak wyglądać ?

2021-04-15 17:40 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +package com.kodilla.ecommercee.repository;public interface UserRepository {
poprawilem

2021-04-16 19:02 UTC, hacker-msl requested changes
w ramach testów do encji - popraw od razu relacje testowanej encji zgodnie z projektem.

2021-04-17 17:32 UTC, hacker-msl requested changes

2021-04-17 17:32 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +@Transactional
pozostali wrzucają @Transactional na każdą metodę osobno. Zróbmy tak, żeby było spójnie

2021-04-17 17:32 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        orderRepository.deleteAll(); */
ten zakomentowany kod wyrzuć.

2021-04-17 17:32 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        Assert.assertEquals((orderId);
tu jest problem w nawiasach

2021-04-17 17:32 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    /* propozycja testów po implementacji serwisów (do korekty w zależności od kodu)
proszę odkomentuj to i popraw PR, żeby uwzględniał uzgodnione relacje,

2021-04-19 05:54 UTC, hacker-msl commented
@Mateusz32   od  dzisiaj Ty jesteś odpowiedzialny za review tego PR (którego autorem jest @ete02 ). Do mnie zgłaszacie dopiero jak @Mateusz32   zatwierdzi lub macie odmienne zdanie w pewnej kwestii. Tam jest taki przycisk "re-review", który wygląda jak recycling. 

![image](https://user-images.githubusercontent.com/44570046/115187775-32312000-a0e4-11eb-8196-01a558fbbe44.png)

Pamiętajcie, żeby go użyć.

2021-04-19 13:51 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +@Transactional
done

2021-04-19 14:02 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        Assert.assertEquals((orderId);
poprawione i zmienione

2021-04-19 14:03 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        orderRepository.deleteAll(); */
done

2021-04-19 14:04 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    /* propozycja testów po implementacji serwisów (do korekty w zależności od kodu)
done

2021-04-19 21:28 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +
może warto usunąc puste wiersze:) kod będzie czytelniejszy

2021-04-19 21:28 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        Assert.assertEquals(2, orderRepository.findAll().size());
Mateusz mi zaproponował zaimportowanie static Assert do aseracji. Tutaj jeszcze bym stworzył listę w której umieściłbym wszystkie pobrane ordery z bazy a potem porównał wielkość listy (.size()) z oczekiwana wartością.

2021-04-19 21:28 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +
te dwa ordery są niepotrzebne skoro przed testami już je stworzyłeś (na samej górze, na początku).

2021-04-19 21:28 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +
tu widzę, że masz wyszukiwanie order'a przez CartId i wypadało by gdzieś stworzyć jakiś obiekt Cart i umieścić go w order'ze przez setter.

2021-04-19 21:28 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +
te dwa ordery są niepotrzebne skoro przed testami już je stworzyłeś (na samej górze, na początku).

2021-04-19 21:28 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    private Order order2 = new Order();
Tworzysz dwa puste obiekty klasy Order. Może warto byłoby umieścić jakieś parametry?

2021-04-19 21:30 UTC, Mateusz32 reviewed
Jak możesz to ustal relacje z encja order jeżeli takie śa potrzbne

2021-04-21 21:22 UTC, Mateusz32 reviewed
Pamietaj o zmianach przy user Dto

2021-04-21 21:22 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Cart Cart;
Czemu zmieniałeś Cart cart na Cart Cart. W sumie to nie jest jakiś szczególny błąd ale zawsze nazwe pola pisze się z małej.

2021-04-21 21:22 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        orderRepository.deleteById(id);
To Clean up jest chyba niepotrzebne skoro nad testem jest @Transactional

2021-04-21 21:22 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        orderRepository.deleteById(id);
To Clean up jest chyba niepotrzebne skoro nad testem jest @transactional

2021-04-21 21:22 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    }
To Clean up jest chyba niepotrzebne skoro nad testem jest @transactional

2021-04-21 21:22 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    }
To Clean up jest chyba niepotrzebne i daj @transactional przed testem

2021-04-21 21:22 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
>      @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
jak tutaj usunąłeś Usera to przy UserDto tez chyba trzeba to zrobic;D

2021-04-21 21:22 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    OrderRepository orderRepository;
dodaj prosze private prze OrderRepository

2021-04-22 17:07 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private Cart Cart;
poprawilem

2021-04-22 17:08 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        orderRepository.deleteById(id);
usunełem

2021-04-22 17:10 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        orderRepository.deleteById(id);
usunełem

2021-04-22 17:10 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    }
usunełem

2021-04-22 17:12 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
>      @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
poprawlem

2021-04-22 17:13 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    OrderRepository orderRepository;
poprawiłem

2021-04-22 17:16 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    }
dodałem

2021-04-22 18:41 UTC, hacker-msl commented
hej @ete02  i @Mateusz32 mogę w czymś pomóc ?

2021-04-24 13:25 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    List<Order> listOfOrders;
dodaj tutaj modyfikator priavate:)

2021-04-24 13:25 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    }*/
usuń komentarz:)

2021-04-24 13:25 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    public void testUserFindAll() {
nad testem powinno być 
@Transacional
@Test
:)

2021-04-24 13:25 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
>      @Transactional
ta adnotacja  @Transactional jest nadmiarowa, możesz ją usunąć:)

2021-04-24 13:48 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    }*/
done

2021-04-24 13:48 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    public void testUserFindAll() {
dodałem

2021-04-24 13:49 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
>      @Transactional
usunięta

2021-04-24 13:49 UTC, ete02 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +    List<Order> listOfOrders;
dodany

2021-04-24 18:12 UTC, Mateusz32 commented
akceptuje

2021-04-24 18:48 UTC, hacker-msl commented
@Mateusz32 musisz kliknąć przycisk "approve" Inaczej nie będziemy w stanie zrobić merge.

2021-04-24 18:53 UTC, hacker-msl requested changes

2021-04-24 18:53 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private Cart cart;
nie może tu być Cart. Ma być `Long cartId `(tak sugerowałem). Ewentualnie `CartDto cartDto` , ale wtedy trudniej pisać mappery.

2021-04-24 18:53 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    public OrderDto(Long id, Long orderNumber, Cart cart) {
można tu użyć konstruktora z lomboka. Trzeba zrobić `Date date = new Date();` w linii 17, pozostałe oznaczyć jako `@NonNull` i dać `@RequiredArgsConstructor`

2021-04-24 20:19 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private Cart cart;
@hacker-msl, ustalilismy wszyscy, ze pomiędzy Order oraz Cart będzie relacje OneToOne, a w tej relacji nie może być uzuty Long. Dlatego nie rozumiem, czy mam również zmieniaćrelacje?

2021-04-25 10:25 UTC, ete02 commented
Nie użyłem Long, bo mam relacje OneToOne, przy której nie może być zastosowany dany typ. Wywaliłem konstruktora i dodałem @NotNull (zgodnie z komentarzem Mateusza) oraz wprowadziłem zmiany do private Date date = new Date();

2021-04-25 18:04 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private Cart cart;
done

2021-04-25 18:04 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +    public OrderDto(Long id, Long orderNumber, Cart cart) {
done

2021-04-25 18:25 UTC, hacker-msl requested changes
przy budowaniu leci WARN,

/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Cart.java:27: warning: @Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. If it is not supposed to be settable during building, make the field final.
    private Map<Product , Integer> productsInCart = new HashMap<>();
                                   ^
1 warning

nad tym polem należy dodać adnotację
@Builder.Default

2021-04-25 18:25 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
czemu EAGER?

2021-04-25 18:27 UTC, Mateusz32 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        order1.setCart(cart1);
powtarzasz dwa razy to samo
Order1.setCart(cart1):)

2021-04-25 18:30 UTC, Mateusz32 submitted a review, later dismissed
Akceptuje

2021-04-25 20:15 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
pobieramy dane, gdy zostaje wykonane zapytanie pobierające nadrzędną część relacji. Domyślnie przy relacji @OneToOne  jest ustawiony FetchType. EAGER. W sumie, zmienłem na LAZY, bo rozumiem, iz chodzi o to oby pobierać dane dopiero wtedy, gdy ich potrzebujemy, czyli  gdy użyjemy gettera na powiązanej kolekcji

2021-04-25 20:26 UTC, Mateusz32 approved these changes

2021-04-26 07:32 UTC, hacker-msl requested changes
testy nie przechodzą (żadne) bo są źle relacje zrobione: 

`Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.kodilla.ecommercee.domain.Cart.user in com.kodilla.ecommercee.domain.User.listCart
	at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:785)
	at org.hibernate.cfg.annotations.CollectionBinder$1.secondPass(CollectionBinder.java:736)
	at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:54)
	at org.hibe`

2021-04-26 11:08 UTC, ete02 commented
@hacker-msl, nie wiem z czym to jest zwiázane, ale u mnie testy przechodzá i dzialaja i buduje sie wszystko https://snipboard.io/L0fd5x.jpg

2021-04-26 11:20 UTC, ete02 commented
hej hacker-msl, Nie wiem co nie tak bo u mnie projekt sie buduje oraz wszsystkie 5 testów są na zielono bez zadnych problemow. Wczoraj wyslalem poprawione klasy oraz testy . zrzut ekranu wysylam https://snipboard.io/L0fd5x.jpg . Nie wiem jak naprawic, skoro u mnie wszsytko przechodzi i w czym może bys problem

2021-04-26 18:53 UTC, hacker-msl submitted a review, later dismissed

2021-04-26 19:02 UTC, hacker-msl approved these changes

2021-04-26 19:02 UTC, merged