Fixed branch JDP210304-1 & JDP210304-12
hacker-msl/project-jdp-2103-04 pull request #37
Opened 2021-04-13 19:10 UTC by brzezyn

Zrobiłem obie poprawki na jednym branchu tj. od komentowałem encję dodałem ProductDto. Nie jestem tylko pewnie co do poprawności użycia BigDecimal.

2021-04-13 19:23 UTC, hacker-msl requested changes

2021-04-13 19:23 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
to musi być odkomentowane, bo jest relacja w Product do tego, która nie jest zakomentowana. Dlatego @ete02  miał problem z budowaniem swojego brancha. Na main już jest poprawione

2021-04-13 19:33 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
tego już nie ma :)

2021-04-13 19:36 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
A na maine tu na GitHubie właśnie cały czas jest zakomentowane.

2021-04-13 19:37 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
no to musisz zostawić: 

    @ManyToOne
     private Group group;

zrób sobie merge z maina najnowszego tutaj: 
git checkout main
git pull origin main
git checkout JDP210304-1a
git merge main

odpal i zobaczysz, ze się wywali build. Odkomentowanie tych 2 linijek naprwia te sytuację.

2021-04-13 19:45 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
a wywalenie w całości tej za komentowanej części? bo ja właśnie to zrobiłem i u mnie całość się buduje.
Maina zaciągałem jakoś krótko po naszej wspólnej rozmowie.

2021-04-13 19:46 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
I ustaliliśmy, że wywalam całość za komentowanego kodu i jak dostaniemy wytyczne co do zależności między encjami to je po prostu dopiszę.

2021-04-14 18:52 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -//    private Group group;
@brzezyn u Ciebie się budoowalo na Twoim branchu. Main też się budował... natomiast po wykonaniu merge main by się przestał budować, co właśnie potwierdziłęm sobie doświadczalnie. jakbyś wykonał te instrukcje, o które prosiłem, to byś sam to zobaczył. W każdym razie problem poprwiłęm i zaraz wrzuce ten kod na maina. Pobierz sobie wtedy maina, zakomentuj te 2 linijki i zobacz co się stanie. Pobrałeś krótko po naszej rozmowie, ale w międzyczasie pojawiły się na nim zmiany, bo pomogłem Eugeniuszowi w rozwiązywaniu problemów z jego kodem.  Były one spowodowane właśnie tym, że relacja Group była zakomentowana. Wiem co ustaliliśmy, ale ... "wszystko płynie" :-)

2021-04-14 18:53 UTC, hacker-msl approved these changes

2021-04-14 18:53 UTC, merged