Testy entity User v1
hacker-msl/project-jdp-2103-04 pull request #38
Opened 2021-04-13 21:44 UTC by Mateusz32

* utworzyłem testy do klasy User; 
* dodałem do klasy User i Order konstruktor, który nie zawiera id i innych pół, które nie były konieczne wg mnie w testach;
* stworzyłem testy dla metod z CrudRepository, które uważałem, że mogą się przydać.

2021-04-14 18:56 UTC, hacker-msl requested changes

2021-04-14 18:56 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    public Order(@NotNull Long orderNumber) {
dodałeś specjalny konstruktor, którego używasz tylko w testach? Nie rób tak. Jeśli już, to użyjmy adnotacji @Builder na encjach z Lomboka.

2021-04-14 18:56 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    public User(@NotNull String userName, @NotNull boolean userValidation, String userKey) {
dodałeś specjalny konstruktor, którego używasz tylko w testach? Nie rób tak. Jeśli już, to użyjmy adnotacji @Builder na encjach z Lomboka.

2021-04-14 18:56 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +    public void testUserSave() {
daj @Transactional na każdy test pracujący z warstwą persystencji jeśli nie piszemy sekcji //clenaup

2021-04-15 15:09 UTC, hacker-msl reviewed
na razie wygląda OK. Czekamy na decyzję w sprawie ustawienia ostatecznych relacji.

2021-04-16 19:03 UTC, hacker-msl requested changes
w ramach testów encji - popraw od razu relacje testowanej encji

2021-04-17 17:27 UTC, hacker-msl requested changes

2021-04-17 17:27 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +        Assert.assertEquals(Optional.of(0L), Optional.of(quantityOfElementsInEntity));
1) tego nie rozumiem, nie można porównać po prostu: 
assertEquals(0L, quantityOfElementsInEntity);  
?? 
2) dodaj static import do assertEquals()

2021-04-17 17:27 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +        Assert.assertEquals(Optional.of(3L), Optional.of(quantityOfElementsInEntity));
po co pakujesz to w optionale  ?

2021-04-19 05:52 UTC, hacker-msl commented
@brzezyn od dzisiaj Ty jesteś odpowiedzialny za review tego PR od @Mateusz32 . Do mnie się zgłaszacie dopiero jak @brzezyn  zrobi "approve" lub macie odmienne zdanie w pewnych kwestiach. Tam jest taki przycisk "re-review", który wygląda jak recycling. 

![image](https://user-images.githubusercontent.com/44570046/115187775-32312000-a0e4-11eb-8196-01a558fbbe44.png)

Pamiętajcie, żeby go użyć.

2021-04-19 15:24 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    public Order(@NotNull Long orderNumber) {
fixed

2021-04-21 13:25 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +}
Mówiliśmy o relacjach w Dto na wczorajszej rozmowie. Tam było na przykładzie klas Product & Group. Było, że do Dto produktu dodać identyfikator grupy. Spróbuj analogicznie pokombinować tutaj :D

2021-04-22 18:41 UTC, hacker-msl commented
hej @brzezyn  i @Mateusz32  czy mogę w czymś pomóc tutaj ?

2021-04-22 21:49 UTC, Mateusz32 commented
Mateusz mam takie pytanko. Bo na rozmowie video wspominałeś o dodaniu w encji Product pole Long groupId (bo taka jest relacja).  Nie bardzo zakumałem to. Mam teraz w encji User pole List<Cart> a w encji Cart pole User user (bo taka relacje ustawiliśmy). W UserDto też dałem pole User user. Czy to jest źle??? Czy mam dodać do UserDto pole Long cartId, a wtedy w encji User zrobi pole List<Cart>listCartID??? Dzięki z góry za pomoc:)

2021-04-24 19:20 UTC, hacker-msl commented
> Mateusz mam takie pytanko. Bo na rozmowie video wspominałeś o dodaniu w encji Product pole Long groupId (bo taka jest relacja). Nie bardzo zakumałem to. Mam teraz w encji User pole List a w encji Cart pole User user (bo taka relacje ustawiliśmy). W UserDto też dałem pole User user. Czy to jest źle??? Czy mam dodać do UserDto pole Long cartId, a wtedy w encji User zrobi pole ListlistCartID??? Dzięki z góry za pomoc:)

@Mateusz32 ja nie przeglądam teraz wszystkich PR co chwilkę. Sprawdzam te, które są "Approved" i o tym mówiłem. Jak chcesz, żebym dostał powiadomienie, że coś piszesz, to użyj nicka z małpą, o tak @hacker-msl .

2021-04-24 19:25 UTC, hacker-msl requested changes

2021-04-24 19:25 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +}
ok, ale to nie jest klasa Dto tylko Entity

2021-04-24 19:25 UTC, hacker-msl commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +public class UserTestSuite {
brakuje testu na Update? miały być testy CRUD (czyli Create/Read/Update/Delete) .

2021-04-24 22:01 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/domain/UserDto.java
> +    private Set<Long> cartsIds;
Dodałem tutaj Set<Long> cartsIds bo encja User ma relacje z encją Cart 1---N

2021-04-25 19:56 UTC, brzezyn approved these changes

2021-04-26 07:28 UTC, hacker-msl approved these changes

2021-04-26 07:28 UTC, merged