Jdp210304 24
hacker-msl/project-jdp-2103-04 pull request #39
Opened 2021-04-14 22:16 UTC by Mateusz32

* OrderController (rzeczywista implementacja);
* OrderMapper;
* OrderService;

2021-04-15 15:12 UTC, hacker-msl requested changes

2021-04-15 15:12 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private final DbOrderService dbOrderService;
w tym PR https://github.com/hacker-msl/project-jdp-2103-04/pull/34/files @KacperB83  zastosował konwencję %NazwaEncji%Service - może zostaniemy przy tym ? czyli OrderService ?

2021-04-15 15:12 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/OrderNotFoundException.java
> +public class OrderNotFoundException extends Exception {
użyj raczej RuntimeException

2021-04-15 22:17 UTC, Mateusz32 reviewed
Poprawiłem zgodnie z zaleceniami

2021-04-15 22:17 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private final DbOrderService dbOrderService;
Fixed

2021-04-15 22:17 UTC, Mateusz32 commented on src/main/java/com/kodilla/ecommercee/controller/OrderNotFoundException.java
> +public class OrderNotFoundException extends Exception {
Fixed

2021-04-16 18:56 UTC, hacker-msl approved these changes

2021-04-16 18:56 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +        Order order = orderMapper.mapToOrder(orderDto);
tutaj implementaja tego end-pointu może zależeć od kwestii relacji z Cart. Na razie zostawiamy.

2021-04-16 18:56 UTC, merged