Jdp210304 21
hacker-msl/project-jdp-2103-04 pull request #41
Opened 2021-04-17 12:15 UTC by brzezyn

Rzeczywista implementacja Product Controller.

2021-04-17 17:06 UTC, hacker-msl requested changes

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto getProduct(@PathVariable String productName) {
1) brakuje obslugi sytuacji, gdy nie ma takiego rekordu
2) z punktu widzenia kompilatora, ten kod będzie OK. Jednak z punktu widzenia serwera HTTP nie do końca, gdyż on nie rozróżnia typu wprowadzonych danych w URL. Trzeba dodać jakiś suffix, np. "/byName" 
3) nazwa parametru w @GetMapping różni się od tej w argumencie metody opatrzonym poprzez @PathVariable

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        productService.deleteProductById(productId);
brak obsługi "brak takiego rekordu"

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        Product product = productService.findProductById(productDto.getProductId());
czemu nie użyłeś tutaj mappera, tylko ręcznie napisałeś aktualizacje poszczególnych zmiennych ?

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    public Product(@NotNull String productName, @NotNull String productDescription, @NotNull BigDecimal price) {
w jakim celu ten konstruktor ?

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                productDto.getProductName(),
tu brakuje ID. W takiej sytuacji nie będziesz mógł użyć mappera do aktualizacji rekordu

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    Product findByProductId(Long productId);
wydaje mi się, że są w JpaRepository zarówno metody getOne jak i findById

2021-04-17 17:06 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      private Group group;
encja Product zawiera encję Group. Natomiast ProductDto nie zawiera ani GroupDto groupDto, ani Long groupId.

2021-04-19 05:50 UTC, hacker-msl commented
@ete02  od  dzisiaj Ty jesteś odpowiedzialny za review tego PR. Do mnie zgłaszacie dopiero jak @ete02  zatwierdzi lub macie odmienne zdanie w pewnej kwestii.

2021-04-19 15:11 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductController() {
dodana

2021-04-19 15:12 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    private ProductMapper productMapper;
okej, poprawię

2021-04-19 15:12 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        return productMapper.mapToProductDto(productService.findProductById(productId));
będzie dodany

2021-04-19 15:13 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +                productDto.getProductName(),
faktycznie zapomniałem o polu z ID

2021-04-19 15:14 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    Product findByProductId(Long productId);
czyli jak są zawarte to nie trzeba ich zapisyawć tak?

2021-04-19 17:37 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
> +    Product findByProductId(Long productId);
można nadpisać przez @Override ale nie jest to koniecznie. Natomiast chyba większość ma bez  metod, więć dla spójnośći może wywal ich. Co sądzisz?

2021-04-20 14:15 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    public Product(@NotNull String productName, @NotNull String productDescription, @NotNull BigDecimal price) {
bez tego konstruktora wywala mi błąd w mapperze

2021-04-20 19:46 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java
>      Product findByProductName(String productName);
W sumie może zostać. Ale pozostałe repo są pustę. Ja bym to  wywalił. Masz w Service, wiec findByProductName bardziej w Product. Co o tym sądzisz?

2021-04-20 19:46 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      }
Jest poprawnie, ale masz adnonatacje konstruktora oraz Setter, więc konstruktor sam to wygeneruje, w związku z czym można wywalić. Jak uważasz?

2021-04-21 16:49 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      }
jak usuwam tę część kodu to wyskakuje mi błąd w mapperze https://snipboard.io/uAEobD.jpg

2021-04-21 16:50 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> -}
poprawię

2021-04-21 16:54 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +       return productMapper.mapToProductDto(savedProduct);
Konkretnie w tym miejscu? Myślałem bardziej, żeby dodać **ProductNotFountException** przy **GetMapping findProductByName** ale wyrzuca mi błąd, że chce konstruktor **orElseThrow** w klasie Product.
A jeżeli miał by być w tym miejscu to żąda konstruktora **orElseThrow** w **ProductDto**

2021-04-21 21:58 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +       return productMapper.mapToProductDto(savedProduct);
Tutaj wszystko ładnie poprawione, NotFound przy GetMapping

2021-04-21 21:58 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        productService.saveProduct(product);
tutaj zrobiłbym coś takiego productService.saveProduct(productService.mapToProduct(productDto));
Jak myślisz?

2021-04-21 21:58 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      }
Z tego co widzę na zrzucie to encja ma już ustawioną relacje i podpiętą listę, której brakuje w Dto. Stąd prawdopodobnie problem. Sprobuj dodać Liste w Dto

2021-04-21 22:00 UTC, ete02 reviewed
V2

2021-04-22 17:34 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        productService.saveProduct(product);
Żeby zrobić w ten sposób InteliiJ wymaga konstruktora w ProductService. Moim zdaniem ta zmiana nie jest konieczna, na razie zostawiam tak jak jest.

2021-04-22 17:36 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
>      }
Chyba sobie poradziłem z tym :D.

2021-04-22 17:50 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        productService.saveProduct(product);
nie jest konieczna, w Service, można dodać @RequiredArgsConstructor. Ale jak uważasz

2021-04-22 18:18 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    //Propozycja zależności
Może warto odkomentować zalezności (na main to chyba tak nie przejdzie) . Jak uważasz?

2021-04-22 18:40 UTC, hacker-msl commented
hej, jak tam? mogę w czymś pomóc @brzezyn  i @ete02   ?

2021-04-22 19:41 UTC, ete02 commented
@hacker-msl jest ok, mamy pewną nieznaczacą rozbieżność ale jutro pewnie zostanie wysłąny na re-review. @brzezyn

2021-04-24 16:54 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        productService.saveProduct(product);
Mam dodaną tę adnotację w Service i mimo tego wyskakiwał błąd. Na razie zostawiamy zobaczymy co na to mentor :D

2021-04-24 19:32 UTC, hacker-msl requested changes

2021-04-24 19:32 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping("/{productName}/")
to nie zadziała w połączeniu z metodą, która pobiera po ID:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Apr 24 21:31:23 CEST 2021
There was an unexpected error (type=Internal Server Error, status=500).
Ambiguous handler methods mapped for '/v1/product/abcd/': {public com.kodilla.ecommercee.domain.ProductDto com.kodilla.ecommercee.controller.ProductController.getProduct(java.lang.String) throws com.kodilla.ecommercee.controller.ProductNotFoundException, public com.kodilla.ecommercee.domain.ProductDto com.kodilla.ecommercee.controller.ProductController.getProduct(java.lang.Long) throws com.kodilla.ecommercee.controller.ProductNotFoundException}

musi być dodane np. /{productName}/byName/ żeby dało się te 2 handlery odróżnić

2021-04-24 19:37 UTC, hacker-msl requested changes
popraw https://github.com/hacker-msl/project-jdp-2103-04/pull/41/files#r619699516

2021-04-25 17:17 UTC, ete02 approved these changes
approve, poprawione zgonie z komentarzem

2021-04-25 18:58 UTC, hacker-msl approved these changes

2021-04-25 18:58 UTC, merged