Jdp210304 22 (group controller rzeczywista implementacja)
hacker-msl/project-jdp-2103-04 pull request #42
Opened 2021-04-19 20:28 UTC by ete02

2021-04-20 18:23 UTC, KacperB83 requested changes

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto createGroup(@RequestBody GroupDto groupDto){return groupDto;
Tworząc encje wszyscy mamy void. Wydaje mi się, że tutaj też tak powinieneś zrobić. Podejrzyj w innych kontrolerach . Stwórz zmienną Group zmapowaną do Group w mapperze a potem zapisz w groupService.save(groupDto)

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @PostMapping
Nie wiem czy jest to niezbędne ale ja dodałem @PostMapping(consumes = APPLICATION_JSON_VALUE)

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroupById(@RequestBody long id) throws GroupNotFoundException{
zmieniłbym na getGroup (bo byId używasz w service) no i chyba tutaj nie potrzebujesz body, nie?

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        );
Nie mogę zejść niżej w komentarzach. 
GroupNotFoundException powinien też pojawić się w deleteGroup, w którym z resztą nić nie usuwasz. Stwórz zmienną Group zmapowaną do Group w mapperze a potem usuń w groupService.deleteGroup(group)

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
>  @Component
Tu chyba trzeba adnotację na @Service zmienić

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +import com.kodilla.ecommercee.domain.Group;
W adnotacjach mam :
@Service i
@RequiredArgsConstructor

2021-04-20 18:23 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +import com.kodilla.ecommercee.domain.Group;
I zakomentowany tekst usuń

2021-04-20 19:45 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        );
Właściwie czy jest w ogóle potrzebne usuwanie grupy produktów? Jak wywalisz grupę to razem z produktami...

2021-04-20 19:58 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto getGroupById(@RequestBody long id) throws GroupNotFoundException{
poprawione

2021-04-20 20:14 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public GroupDto createGroup(@RequestBody GroupDto groupDto){return groupDto;
poprawione

2021-04-20 20:28 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        );
Grupa produktow może być rózna, np, sezonowe towary,, grupa może zostać usuniętę, bo załozmy juz nie proponujemy, ale produkty pozostają tylko przerzucamy do innej grupy

2021-04-20 20:30 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        );
GroupNotFoundException dopasowałem do OrderController, który zostal zaakceptowany i wysłany na main przez Mateusza.

2021-04-20 20:33 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
>  @Component
done

2021-04-20 20:56 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      }
resolved

2021-04-20 21:02 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @PostMapping
mogę dodać @PostMapping, ale wtedy usuwam @RequestMapping(method = RequestMethod.POST, - bo jest to samo

2021-04-21 07:19 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @PostMapping
Dokładnie. Mateusz prosił żebyśmy korzystali ze skróconych adnotacji

2021-04-21 07:39 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
Tu musisz poprawić :
Zerknij na CreateOrder
Order order = orderMapper.mapToOrder(orderDto);
        orderService.saveOrder(order);
Ja mam tak samo. Mateusz zwracał nam uwagę by najpierw tworzyć zmienną a potem, stosować metodę z Service i ewentualnie zwracać Dto z mappera jeżeli nie jest to void

2021-04-21 07:39 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
tzn. musisz... nie musisz bo wychodzi na to samo ale możesz :-)

2021-04-21 07:39 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
>  @Transactional
Tą adnotację możesz usunąć. Będzie w testach

2021-04-21 07:39 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
>  @Transactional
@Transactional

2021-04-21 07:39 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroupById")
Tu też zmień na @GetMapping

2021-04-21 07:39 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteGroup(groupId);
Tu dalej mam wątpliwość czy możesz usunąć, właściwie czy jest sens usuwania grupy. Co się stanie ze wszystkimi produktami przypisanymi do tej grupy? Trzeba zapytać Mateusza.

2021-04-21 17:32 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.saveGroup(groupMapper.mapToGroup(groupDto));
done

2021-04-21 17:52 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
>  @Transactional
nie mogę usunąć, bo to powoduje bład w Controlerze i servisie. Jesli usuwam to trzeba zmienić W servise usunąć metodę statyczna, a to powoduje , iz w kontrolerze w @PostMapping wyswietla bład Non-static method 'saveGroup(com.kodilla.ecommercee.domain.Group)' cannot be referenced from a static context , co zmusza mnie do przewrocenie metody statycznej oraz zachowanie @transactional

2021-04-21 18:11 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
>  @Transactional
done

2021-04-21 18:11 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      @RequestMapping(method = RequestMethod.GET, value = "getGroupById")
done

2021-04-21 18:13 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteGroup(groupId);
uważam ,ze powinna być mozliwość usuniecie grupy, w zaden sposó to nie oznacza ze zostną usunięte produkty. Sklep może zdecydować, ze nie będzię sprzedawał pewnej grupy produtó w etc.

2021-04-21 20:05 UTC, KacperB83 approved these changes
Zrobiłem 3 review i Eugeniusz wszystko poprawił. Mam nadzieję, że wszystkie większe rzeczy zauważyłem. pzdr. K

2021-04-21 20:06 UTC, merged