Jdp210304 22 (group controller rzeczywista implementacja)
hacker-msl/project-jdp-2103-04 pull request #43
Opened 2021-04-22 18:33 UTC by hacker-msl

Jdp210304 22 (group controller rzeczywista implementacja)

2021-04-22 18:46 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping(value = "getGroupById")
value z nazwą powinno wylecieć... powinien być "/{groupId}/" . do tego raczej pobierania parametru ID z @RequestBody przy @Get nie jest raczej fajnym pomysłem. Tutaj podepnij @PathVariable. Skąd ta zmiana? to mieliśmy ustalone.

2021-04-22 18:46 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<Product> productDtos;
jeśli chcecie w GroupDto dołożyć listę produktów, to albo to muszą być same IDki albo ProductDto

2021-04-22 19:33 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping(value = "getGroupById")
przewruciłem

2021-04-22 19:33 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<Product> productDtos;
poprawiłem

2021-04-22 20:26 UTC, KacperB83 requested changes

2021-04-22 20:26 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping("{/getGroupById/}")
tu pewnie powinno być samo "/id"

2021-04-22 20:26 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private Long productId;
Chyba nadal powinna być lista? Ale List<Long> productsId;

2021-04-22 20:27 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private Long productId;
List<Long> productsId;

2021-04-22 20:52 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private Long productId;
poprawione,

2021-04-22 21:00 UTC, KacperB83 submitted a review, later dismissed

2021-04-23 19:13 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping("{/getGroupById/}")
tak, do poprawki

2021-04-23 19:13 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List productsId;
tu chyba powinno być: 
List<Long> productsIds. Nie używaj "surowych" typów w kolekcjach.

2021-04-24 00:19 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List productsId;
poprawione

2021-04-24 00:26 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping("{/getGroupById/}")
poprawione

2021-04-24 08:18 UTC, KacperB83 approved these changes

2021-04-24 19:43 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    List productsIds;
nie powinno być surowego typu List, daj List<Long> productsIds

2021-04-24 19:53 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    List productsIds;
@hacker-msl, nie koniecznie rozumiem? na początku miałem private List productsIds, napisałeś, ze  daj List productsIds, wieć usunełem private. Rozumiem, że z powrotem mam dodać private . Szczerze to pogubiłem się juz w tym

2021-04-24 21:59 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    List productsIds;
Nie zauważyłem. Pewnie Mateuszowi chodziło o typ. Powinno być 
private List<Long> productsIds;

2021-04-24 22:00 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    List productsIds;
kurde obcina nawiasy i wywala Long - private List Long productsIds;

2021-04-24 23:09 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    List productsIds;
done

2021-04-25 06:27 UTC, KacperB83 approved these changes

2021-04-25 06:31 UTC, KacperB83 submitted a review, later dismissed

2021-04-25 06:31 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private Date date = new Date();
Ta data jest potrzebna?

2021-04-25 07:44 UTC, ete02 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private Date date = new Date();
wywyliłem, poprawilem List<Long> na List<Product> bo Mapper nie przyjmował <Long>, dodałem Getter oraz Setter, tak jak RequeiredArgConstructor, nie może być zostosowany , ze wzgłedu na klase Group

2021-04-25 08:10 UTC, KacperB83 approved these changes

2021-04-25 09:21 UTC, KacperB83 submitted a review, later dismissed

2021-04-25 19:03 UTC, hacker-msl reviewed
popraw @ete02  :-) prawie to mamy, jutro zrobimy merge

2021-04-25 19:03 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping("{/id/}")
chyba `@GetMapping("/{id}/")` ma być

2021-04-25 19:03 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping("{/id/}")
@ete02 @KacperB83

2021-04-26 07:42 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    @GetMapping("{/id/}")
rozwiązane poprzez merge z maina @ete02 oraz @KacperB83

2021-04-26 07:44 UTC, merged