Group - testy encji po poprawkach
hacker-msl/project-jdp-2103-04 pull request #48
Opened 2021-04-24 20:27 UTC by KacperB83

Poprawione. Dodałem 2 testy. Dzięki za review

2021-04-25 18:31 UTC, hacker-msl requested changes
u mnie leci błąd testu:
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.kodilla.ecommercee.groupTestSuite.GroupTestSuite.testSaveGroups(GroupTestSuite.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

2021-04-25 20:19 UTC, KacperB83 commented
Poprawiłem. Nie zauważyłem, że przypadkiem usunąłem save dla drugiej grupy

2021-04-25 20:34 UTC, Mateusz32 approved these changes

2021-04-26 07:33 UTC, hacker-msl approved these changes

2021-04-26 07:33 UTC, merged