"CartController - wstępna implementacja endpointów"
hacker-msl/project-jdp-2103-04 pull request #6
Opened 2021-04-02 18:21 UTC by KacperB83

2021-04-03 18:22 UTC, hacker-msl requested changes

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @GetMapping("cart")
nie używaj value w takiej sytuacji, jeśli zwracany jest 1 obiekt to w value powinno być "/{id}/" oraz w argumencie wejściowym @PathVariable Long id

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @DeleteMapping("emptyCart")
nie używaj value tutaj, dodatkowo czy na pewno cały obiekt CartDto musi być przyjmowany tutaj ?

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @DeleteMapping("emptyCart")
w kontrolerach z innych PR przy @Delete zwracany jest void. Warto to ujednolicić

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PutMapping("cart/addProduct")
może addProductToCart ?

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PutMapping("cart/deleteProduct")
delete z metodą HTTP "PUT" ? dlaczego ?

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +public class Cart {
encja nie miała być częścią tego zadania ?

2021-04-03 18:22 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +@RequestMapping("/v1/ecommercee")
dodaj @CrossOrigin("*")

2021-04-03 18:28 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +@RestController
dodaj @CrossOrigin("*")

2021-04-04 17:16 UTC, hacker-msl requested changes

2021-04-04 17:16 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @PutMapping("/{id}/addProductToCart")
metoda nazywa się teraz addProductToCart a przyjmuje cały CartDto i jego ID... czy na pewno tak ma być ?

2021-04-04 17:16 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
>  public class Cart {
wyrzuć encję z tego PR, bo to nie jest element tego zadania.

2021-04-05 16:56 UTC, hacker-msl requested changes

2021-04-05 16:56 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public CartDto addProductToCart(@PathVariable String id) {
w mojej ocenie metoda ta skoro dodaje jakiś produkt, powinna w parametrze przyjmować ProductDto, prawda? możesz założyć pustą klasę  ProductDto

2021-04-05 16:56 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
>  package com.kodilla.ecommercee;
może zróbmy jakiś pakiet pod te klasę i inne? Sugeruję pakiet com.kodilla.ecommercee.controller

2021-04-06 19:21 UTC, hacker-msl requested changes

2021-04-06 19:21 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +@RequiredArgsConstructor
a to nie jest chyba tutaj potrzebne

2021-04-06 19:21 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PutMapping("addProductToCart")
mam wrażenie, że 3 raz piszę jak to ma być zrobione... wyrzuć value z @PutMapping oraz dodaj @RequestBody do parametru wejściowego metody

2021-04-06 19:21 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @DeleteMapping("deleteProductFromCart")
mam wrażenie, że 3 raz piszę jak to ma być zrobione... zmień na /{productId}/ oraz dorzuć @PathVariable do atrybutu Long productId

2021-04-06 19:21 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PostMapping("createCart")
wyrzuć value z adnotacji @PostMapping

2021-04-06 19:58 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +@RequiredArgsConstructor
usuwam

2021-04-06 20:05 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PutMapping("addProductToCart")
źle Ciebie zrozumiałem w ostatnim komentarzu. Poprawiam

2021-04-06 20:28 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @DeleteMapping("deleteProductFromCart")
poprawione ale mam wątpliwość taką czy jeżeli :
@DeleteMapping()
    public void emptyCart(@PathVariable Long id) {    }

@DeleteMapping("/{productId}")
    public void deleteProductFromCart(@PathVariable Long productId) {    }

będę wpisywał adres tak samo DELETE http://localhost:8080/v1/cart/1 - nie powinienem w tym drugim przypadku dodać value "deleteProduct/{id}"?

2021-04-07 19:00 UTC, hacker-msl requested changes

2021-04-07 19:00 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @DeleteMapping()
te nawiasy nie są potrzebne...

2021-04-07 19:00 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PutMapping()
te nawiasy nie są potrzebne...

2021-04-07 19:00 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PostMapping()
te nawiasy nie są potrzebne...

2021-04-07 19:00 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<String> productsInCart;
a nie lepiej wrzucić tutaj List<ProductDto> lub po prostu List<Long> i zmienić nazwę na productsIds ?

2021-04-07 21:15 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<String> productsInCart;
Nie wiem czy dobrze rozumiem - CartDto ma mieć private List<Long> productsIds;?

2021-04-07 21:15 UTC, KacperB83 commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private int cartValue;
Myślałem, że ma przesłać  wartość koszyka - źle to rozumiem?

2021-04-09 19:51 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private List<String> productsInCart;
no tak... uważasz, że trzymanie produktów jako String to dobry pomysł @KacperB83  ?

2021-04-09 19:51 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private int cartValue;
ok, ale nazwa trochę niezbyt intuicyjna

2021-04-09 19:54 UTC, hacker-msl submitted a review, later dismissed

2021-04-09 19:56 UTC, hacker-msl approved these changes

2021-04-09 19:56 UTC, merged