Created UserController and domain classes
hacker-msl/project-jdp-2103-04 pull request #8
Opened 2021-04-03 06:56 UTC by robertgluszkiewicz

1. Nie jestem pewny czy w polach klasy UserDto trzymać wartość pola userKey i status walidacji.

2. Świadomie nie chciałem użyć metody PUT (która zmienia wszystkie właściwości obiektu) tylko metody PATCH, aby zmieniał się tylko status walidacji usera lub jego klucz. Nie wiem natomiast jak w argumencie metody określić, która właściwość będzie zmieniana, jako @Param?). Ponadto userkey nie powinien być chyba wystawiony "na świat" w value :-)
3. Wydaję mi się, że w moim kontrolerze dopiero w pełnej implementacji będę mógł poprawnie wykorzystać PATCH, a obecnie metody zwracają i tak cały nowy obiekt DTO.

2021-04-03 17:41 UTC, hacker-msl requested changes
1. na razie tak zostaw, ale w bardziej profesjonalnym rozwiązaniu to powinno faktycznie wylecieć. 
2. Albo robisz osobne DTO albo dodajesz jakiś argument, który czyta ciało requestu.
3. ok

2021-04-03 17:41 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PatchMapping("/{id}/status/")
jeśli ma się nazywać /status/ to powinna taka metoda przyjmować jakiś status. Jeśli ma tylko blokować użytkownika, to nazwij ten mapping /block/

2021-04-03 17:41 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +@RequestMapping("/v1/ecommercee")
czemu taka dziwna nazwa? chyba lepiej /v1/user ?

2021-04-03 18:27 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/User.java
> +public class User {
encja nie była częścią tego zadania

2021-04-03 18:27 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +@RestController
dodaj @CrossOrigin("*")

2021-04-04 17:19 UTC, hacker-msl commented
@robertgluszkiewicz  coś tu się dzieje ?

2021-04-04 18:40 UTC, robertgluszkiewicz commented
Przeczytałem uwagi. Do jutra jestem bez komputera. Zgodnie z zaleceniami Kodilli uprzedziłem o tym zespół w moim daily.

2021-04-05 16:59 UTC, hacker-msl requested changes

2021-04-05 16:59 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/User.java
> +package com.kodilla.ecommercee;
może zróbmy jakiś pakiet pod te klasę i inne? Sugeruję pakiet com.kodilla.ecommercee.domain

2021-04-05 16:59 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/UserController.java
>  package com.kodilla.ecommercee;
może zróbmy jakiś pakiet pod te klasę i inne? Sugeruję pakiet com.kodilla.ecommercee.controller

2021-04-05 16:59 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/User.java
> +public class User {
wyrzuć te klasę  z tego PR

2021-04-06 19:18 UTC, hacker-msl approved these changes

2021-04-06 19:18 UTC, merged

2021-04-07 16:04 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +    @PatchMapping("/{id}/status/")
OK

2021-04-07 16:04 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +@RequestMapping("/v1/ecommercee")
Zgadza się.

2021-04-07 16:04 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/User.java
> +public class User {
OK

2021-04-07 16:04 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/UserController.java
> +@RestController
OK

2021-04-07 16:05 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/User.java
> +package com.kodilla.ecommercee;
OK

2021-04-07 16:05 UTC, robertgluszkiewicz commented on src/main/java/com/kodilla/ecommercee/UserController.java
>  package com.kodilla.ecommercee;
OK