JDP210304-1
hacker-msl/project-jdp-2103-04 pull request #9
Opened 2021-04-03 12:42 UTC by brzezyn

2021-04-03 17:32 UTC, hacker-msl requested changes

2021-04-03 17:32 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getProducts")
użyj krótkich adnotacji jak @GetMapping, nie używaj value w tym miejscu. poczytaj zalecenia na kanale zespołowym.

2021-04-03 17:32 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getProduct")
użyj krótkich adnotacji jak @GetMapping, nie używaj value w tym miejscu. poczytaj zalecenia na kanale zespołowym. 
jako value daj "/{productId}/" oraz dodaj @PathVariable do argumentu wejśćiowego metody

2021-04-03 17:32 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.DELETE, value = "deleteProduct")
użyj krótkich adnotacji jak @DeleteMapping, nie używaj value w tym miejscu. poczytaj zalecenia na kanale zespołowym. 
jako value daj "/{productId}/" oraz dodaj @PathVariable do argumentu wejśćiowego metody

2021-04-03 17:32 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "updateProduct")
jak wyżej

2021-04-03 17:32 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @RequestMapping(method = RequestMethod.POST, value = "createProduct")
jak wyżej

2021-04-03 18:27 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +@RestController
dodaj @CrossOrigin("*")

2021-04-04 17:19 UTC, hacker-msl requested changes

2021-04-04 17:19 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +@RestController
miało być CrossOrigin z * w środku

2021-04-04 17:19 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @PutMapping("/{productId}/")
tutaj {productId} nie jest potrzebny w PathVariable bo przychodzi z ProductDto

2021-04-04 17:19 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public ProductDto updateProduct(@PathVariable ProductDto productDto) {
tutaj raczej Dto w PathVariable nie prześlesz. Do tego nie zgadza się nazwa productDto <> productId. Powinno być raczej @RequestBody

2021-04-05 16:53 UTC, hacker-msl requested changes

2021-04-05 16:53 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping()
te nawiasy nie są potrzebne

2021-04-05 16:53 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @PostMapping("/{productId}/")
ten mapping jest błędny... value nie jest tu wymagane w ogóle bo ID leci w DTO

2021-04-05 16:53 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +public class ProductDto {
Dto ma wylecieć z tego PR, do tego jest osobny ticket...

2021-04-05 19:35 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    @GetMapping()
faktycznie zapomniałem ich usunąć

2021-04-05 19:36 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +public class ProductDto {
W bootcampie'e w momence tworzenia TaskController musieliśmy mieć klasę Task i TaskDto dlatego wpisałem ją przy tworzeniu kontrolera.

2021-04-05 20:57 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private double price;
zmieniłem int na doubla bo przecież cena może być może być liczbą z przecinkiem :D

2021-04-06 19:25 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +public class ProductDto {
ok, ale tu jej nie musisz mieć

2021-04-06 19:26 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private double price;
no double to też jakiś super tu nie jest :P ale niech będzie

2021-04-06 19:28 UTC, hacker-msl requested changes

2021-04-06 19:28 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void createProduct(@PathVariable ProductDto productDto) {
no raczej nie wrzucisz całego obiektu Dto w ścieżce URLa. Tzn teoretycznie jest to wykonywalne, ale z pewnymi ograniczeniami. Co gorsza - różnymi, w różnych przeglądarkach. WIęc się tego nie robi. Tutaj powinno być @RequestBody.

2021-04-06 21:17 UTC, brzezyn commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void createProduct(@PathVariable ProductDto productDto) {
Okej, poprawione

2021-04-07 19:32 UTC, hacker-msl requested changes
branch się nie buduje ... 

/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:3: error: package lombok does not exist
import lombok.AllArgsConstructor;
             ^
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:4: error: package lombok does not exist
import lombok.Getter;
             ^
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:6: error: cannot find symbol
@Getter
 ^
  symbol: class Getter
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/domain/Product.java:7: error: cannot find symbol
@AllArgsConstructor
 ^
  symbol: class AllArgsConstructor
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:13: error: cannot find symbol
    public List<ProductDto> getProducts() {
           ^
  symbol:   class List
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:13: error: cannot find symbol
    public List<ProductDto> getProducts() {
                ^
  symbol:   class ProductDto
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:17: error: cannot find symbol
    public ProductDto getProduct(@PathVariable Long productId) {
           ^
  symbol:   class ProductDto
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:25: error: cannot find symbol
    public ProductDto updateProduct(@RequestBody ProductDto productDto) {
                                                 ^
  symbol:   class ProductDto
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:25: error: cannot find symbol
    public ProductDto updateProduct(@RequestBody ProductDto productDto) {
           ^
  symbol:   class ProductDto
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:29: error: cannot find symbol
    public void createProduct(@RequestBody ProductDto productDto) {
                                           ^
  symbol:   class ProductDto
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:18: error: cannot find symbol
        return new ProductDto(1L, "name", "description", 1.0);
                   ^
  symbol:   class ProductDto
  location: class ProductController
/home/mateo/eclipse-workspace/kodilla-team/project-jdp-2103-04/src/main/java/com/kodilla/ecommercee/controller/ProductController.java:26: error: cannot find symbol
        return new ProductDto(1L, "name", "description", 1.0);
                   ^
  symbol:   class ProductDto
  location: class ProductController
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

2021-04-07 21:20 UTC, brzezyn commented
Dodałem do PR build.gradle bo możliwe, że przez to się nie budowało.

2021-04-08 18:20 UTC, hacker-msl commented
@brzezyn tak, żebym mógł zatwierdzić PR i zrobić merge, to branch musi się budować. Dodaj pustą klasę Dto w pakiecie domain

2021-04-08 18:22 UTC, hacker-msl requested changes
branch musi się budować

2021-04-08 22:07 UTC, brzezyn commented
Dto musi być pełne inaczej się nie buduje. Z tego co zauważyłem Controller Order i User też musiały być z Dto.

2021-04-08 22:15 UTC, brzezyn commented
okej wróć, zrobiłem puste Dto ale musiałem usunąć też wartości w @GetMapping & @PutMapping. Ale wszystko wygląda okej powinno być dobrze :D

2021-04-09 19:32 UTC, hacker-msl approved these changes

2021-04-09 19:32 UTC, merged